[build]
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/:shortId"
  to = "https://short-x.onrender.com/:shortId"
  status = 200
  force = true
  headers = {Host = ":host"}