/** @type {import('tailwindcss').Config} */
export default {
  mode: "jit",
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',  // Asegúrate de que Tailwind esté procesando todos los archivos
  ],
  darkMode: "selector",
  safelist: [
    "bg-tech-Reactjs",
    "bg-tech-ReactjsDark",
    "bg-tech-ReactRouter",
    "bg-tech-ReactRouterDark",
    "bg-tech-TailwindCSS",
    "bg-tech-TailwindCSSDark",
    "bg-tech-FramerMotion",
    "bg-tech-FramerMotionDark",
    "bg-tech-Chartjs",
    "bg-tech-ChartjsDark",
    "bg-tech-Axios",
    "bg-tech-AxiosDark",
    "bg-tech-Libphonenumberjs",
    "bg-tech-LibphonenumberjsDark",
    "bg-tech-JSONWeb",
    "bg-tech-JSONWebDark",
    "bg-tech-Stripe",
    "bg-tech-StripeDark",
    "bg-tech-Vite",
    "bg-tech-ViteDark",
    "bg-tech-Nodejs",
    "bg-tech-NodejsDark",
    "bg-tech-Expressjs",
    "bg-tech-ExpressjsDark",
    "bg-tech-MongoDB",
    "bg-tech-MongoDBDark",
    "bg-tech-Mongoose",
    "bg-tech-MongooseDark",
    "bg-tech-JWT",
    "bg-tech-JWTDark",
    "bg-tech-Nodemailer",
    "bg-tech-NodemailerDark",
    "bg-tech-SocketIO",
    "bg-tech-SocketIODark",
    "bg-tech-CORS",
    "bg-tech-CORS_Dark",
    "bg-tech-Swagger",
    "bg-tech-SwaggerDark",
    "bg-tech-Jest",
    "bg-tech-JestDark"
  ],
  theme: {
    extend: {
      boxShadow: {
        // "inner-left-top": "inset 10px 5px 10px -5px rgba(112, 128, 144, 0.2), inset 5px 10px 10px -5px rgba(112, 128, 144, 0.2)",
      },
      colors: {
        link: "#FFC107",
        light: {
          background: "#F0F4F8",
          primary: "#BCCCE0",
          secondary: "#9FB3C8",
          accent: "#3A5F8F",
          title: "#1A252F",
          subtitle: "#34495E",
          paragraph: "#4A6071",
          generalText: "#2C3E50",
          active: "#0E6655",
        },
        dark: {
          background: "#1A2633",
          primary: "#2E4057",
          secondary: "#3C5A77",
          accent: "#6C8AB6",
          title: "#FFFFFF",
          subtitle: "#BFC3C4",
          paragraph: "#A9ADB0",
          generalText: "#D0D3D4",
          active: "#16A085",
        },
        tech: {
          Reactjs: "#ABE8FF",
          ReactjsDark: "#61DAFB",
          ReactRouter: "#E57373",
          ReactRouterDark: "#CA4245",
          TailwindCSS: "#90E0EF",
          TailwindCSSDark: "#38BDF8 ",
          FramerMotion: "#F88E72",
          FramerMotionDark: "#F05A28",
          Chartjs: "#FFA5B1",
          ChartjsDark: "#FF6384",
          Axios: "#9C71E0",
          AxiosDark: "#671DDF",
          Libphonenumberjs: "#FF8A65",
          LibphonenumberjsDark: "#E64A19",
          JSONWeb: "#555555",
          JSONWebDark: "#000000",
          Stripe: "#008CFC",
          StripeDark: "#006BB3",
          Vite: "#A5A9FF",
          ViteDark: "#646CFF",
          Nodejs: "#68A063",
          NodejsDark: "#3C9D3D",
          Expressjs: "#000000",
          ExpressjsDark: "#3F3F3F",
          MongoDB: "#47A248",
          MongoDBDark: "#3E8E41",
          Mongoose: "#6CBBF2",
          MongooseDark: "#4F99CC",
          JWT: "#000000",
          JWTDark: "#333333",
          Nodemailer: "#D14836",
          NodemailerDark: "#B02E1A",
          SocketIO: "#000000",
          SocketIODark: "#333333",
          CORS: "#F7A800",
          CORS_Dark: "#C67A00",
          Swagger: "#85EA2D",
          SwaggerDark: "#5EAC24",
          Jest: "#C21325",
          JestDark: "#9A0F1F",
        },
      },
      backgroundImage: {
        "btn-light-mode-1": "linear-gradient(45deg, #3A5F8F, #BCCCE0)",
        "btn-light-mode-2": "linear-gradient(45deg, #2C3E50, #AAB8C2)",
        "btn-dark-mode-1": "linear-gradient(45deg, #7F9AB8, #34495E)",
        "btn-dark-mode-2": "linear-gradient(45deg, #5D6D7E, #2C3E50)",
        "btn-dark-mode-3": "linear-gradient(45deg, #6C8AB6, #1A2633)",
        "btn-dark-mode-4": "linear-gradient(45deg, #3C5A77, #2E4057)",
        "btn-dark-mode-5": "linear-gradient(45deg, #3A5F8F, #1A2633)",
      },
      opacity: {
        light: "0.3",
        dark: "0.1",
      },
    },
  },
  plugins: [],
};
